### ISSUE TITLE
Add match-like assertion

### ISSUE THREAD

**Issue by pyrmont** [pyrmont/testament#5]
@yumaikas has requested that Testament include a `match`-like assertion. The API would look like:

```clojure
(assert-match expect-structure actual-value &opt note)
```

An example usage: 

```clojure
(assert-match { :month-day 28 } (os/date) "The date includes a `:month-day` key")
```

The assertion would pass if `expect-structure` partially matched the actual structure of `actual-value` (rather than an exact match).

**Comment by pyrmont** [comment]
@andrewchambers pointed out that Rust has a `matches!` macro that has a similar intended use.

```clojure
(assert (matches (os/date) {:month-day 28}))
```

**Comment by andrewchambers** [comment]
my idea kind of relies on matches being added to the main janet to make sense.

**Comment by pyrmont** [comment]
@andrewchambers Since `is` is a macro in Testament, though, I think I could use the `matches` symbol to identify this as a call to (a hypothetical) `assert-matches*` function and perhaps do something similar :)
